[[redirects]]
  from = "/api/*"
  to = "https://relieved-kilt-fly.cyclic.app/api/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"

  
