const baseUrl = "/api/v1/";

export const URLS = {
  login: `${baseUrl}login`,
  addUser: `${baseUrl}addUser`,
  getUser: `${baseUrl}getUser`,
  addProductCategory: `${baseUrl}addProductCategory`,
  getProductCategory: `${baseUrl}getProductCategory`,
  updateProductCategory: `${baseUrl}updateProductCategory`,
  deleteProductCategory: `${baseUrl}deleteProductCategory`,
  addStore: `${baseUrl}addStore`,
  getStore: `${baseUrl}getStore`,
  updateStore: `${baseUrl}updateStore`,
  deleteStore: `${baseUrl}deleteStore`,

  getProduct: `${baseUrl}getProduct`,
  getBrand: `${baseUrl}getBrand`,
  addBrand: `${baseUrl}addBrand`,
  updateBrand: `${baseUrl}updateBrand`,
  deleteBrand: `${baseUrl}deleteBrand`,
  addProduct: `${baseUrl}addProduct`,
  updateProduct: `${baseUrl}updateProduct`,
  deleteProduct: `${baseUrl}deleteProduct`,
  getCustomer: `${baseUrl}getCustomer`,
  addCustomer: `${baseUrl}addCustomer`,
  addSales: `${baseUrl}addSales`,
  updateSales: `${baseUrl}updateSales`,
  getSales: `${baseUrl}getSales`,
  deleteSales: `${baseUrl}deleteSales`,
  updateUser: `${baseUrl}updateUser`,
  getProductByCategory: `${baseUrl}getProductByCategory`,
  addDummySales: `${baseUrl}addDummySales`,
  getDummySales: `${baseUrl}getDummySales`,
  dummyDeleteSales: `${baseUrl}dummyDeleteSales`,
  getCompanyDetails: `${baseUrl}getCompanyDetails`,
  addCompanyDetails: `${baseUrl}addCompanyDetails`,
  updatePassword: `${baseUrl}updatePassword`,
  uploadAvatar: `${baseUrl}uploadAvatar`,
  deleteCustomer: `${baseUrl}deleteCustomer`,
  addInvoice: `${baseUrl}addInvoice`,
  getInvoice: `${baseUrl}getInvoice`,
  deleteInvoice: `${baseUrl}deleteInvoice`,
  updateInvoice: `${baseUrl}updateInvoice`,

};
